TITLE ATIV8
.MODEL small
.STACK 100h
.DATA
MSG1 DB "INSIRA UMA SEQUENCIA DE 1S E 0S:$"
.CODE
MAIN PROC
MOV AX, @DATA
MOV DS, AX

;IMPRIME A MSG1 NA TELA
MOV AH,9
LEA DX, MSG1
INT 21H

;ZERA BX
XOR BX,BX
;ZERA CX
MOV CX,17
;LÊ CADA CARACTER DIGITADO
MOV AH,1

LERCARACTER:
;SOMA 1 EM CX
;COMPARA CX COM 16
CMP CX,0
;SE CX FOR MAIOR QUE 16, OU SEJA, O USUARIO INSERIU MAIS QUE 16 CARACTERES, O PROGRAMA É FINALIZADO
JE TRANSFORMOU
;TERMINA DE LER O CARACTER INSERIDO SE NAO O CONTADOR DE CARACTERES DIGITADO (cx) NAO PASSAR DE 16
INT 21H
;COMPARA O CARACTER LIDO COM ENTER (CARRIAGE RETURN - 13 NA TABELA ASCII)
CMP AL,13D
;SE O ENTER FOI DIGITADO (OU SEJA, SE AL FOR IGUAL A 13), PULA PRA FUNÇÃO QUE FINALIZA O PROGRAMA
JE TRANSFORMOU
;TRANSFORMA O CARACTER LIDO NO SEU BINARIO CORRESPONDENTE (EX: TRANSFORMA 1 EM 0001)
AND AL,0FH
;DESLOCA UM PARA A ESQUERDA
SHL BX,1
;COMPARA AL (O CARACTER QUE ACABOU DE SER DIGITADO)COM 1
OR BL,AL 
;SE O ULTIMO CARACTER DIGITADO (AL) FOR 1, PULA PARA A FUNÇÃO UM
LOOP  LERCARACTER


;FINALIZA O PROGRAMA
TRANSFORMOU:
MOV AH,4CH
INT 21H
MAIN ENDP 
END MAIN


